# fly.toml file generated for animodibs on 2023-04-16T10:20:40+08:00

app = "animodibs"
primary_region = "sin"
kill_signal = "SIGTERM"
kill_timeout = 120

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[deploy]
  release_command = "bundle exec rails db:migrate"

[http_service]
  internal_port = 8080
  force_https = true
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true  # optional